export type OnboardingScreensType = {
  id: number;
  image: any;
  title: string;
  desc: string;
};

export type MovieDetailsType = {
  poster_path: string;
  backdrop_path: string;
  title: string;
  overview: string;
  vote_average: string;
  id: number;
};

export const onboarding_screens: OnboardingScreensType[] = [
  {
    id: 1,
    image: require("@/assets/images/splash_1.png"),
    title: "Watch Movies",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In dapibus varius nulla, quis dictum augue.",
  },
  {
    id: 2,
    image: require("@/assets/images/splash_2.png"),
    title: "Search Movies",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In dapibus varius nulla, quis dictum augue.",
  },
  {
    id: 3,
    image: require("@/assets/images/splash_3.png"),
    title: "Download Movies",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In dapibus varius nulla, quis dictum augue.",
  },
];

export const sampleData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg",
      genre_ids: [28, 18, 36],
      id: 14537,
      original_language: "ja",
      original_title: "切腹",
      overview:
        "Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.",
      popularity: 18.081,
      poster_path: "/5konZnIbcAxZjP616Cz5o9bKEfW.jpg",
      release_date: "1962-09-15",
      title: "Harakiri",
      video: false,
      vote_average: 8.4,
      vote_count: 947,
    },
    {
      adult: false,
      backdrop_path: "/aJCtkxLLzkk1pECehVjKHA2lBgw.jpg",
      genre_ids: [12, 28, 878],
      id: 1891,
      original_language: "en",
      original_title: "The Empire Strikes Back",
      overview:
        "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
      popularity: 32.885,
      poster_path: "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
      release_date: "1980-05-20",
      title: "The Empire Strikes Back",
      video: false,
      vote_average: 8.4,
      vote_count: 16553,
    },
    {
      adult: false,
      backdrop_path: "/dVr11o9or7AS8AMPfwjSpEU83iU.jpg",
      genre_ids: [18, 10752],
      id: 423,
      original_language: "en",
      original_title: "The Pianist",
      overview:
        "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
      popularity: 45.136,
      poster_path: "/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
      release_date: "2002-09-17",
      title: "The Pianist",
      video: false,
      vote_average: 8.385,
      vote_count: 8915,
    },
    {
      adult: false,
      backdrop_path: "/x9jRnHZlmApkYFMz2mc1E0cfTz9.jpg",
      genre_ids: [18, 10402],
      id: 244786,
      original_language: "en",
      original_title: "Whiplash",
      overview:
        "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
      popularity: 116.451,
      poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
      release_date: "2014-10-10",
      title: "Whiplash",
      video: false,
      vote_average: 8.381,
      vote_count: 14706,
    },
    {
      adult: false,
      backdrop_path: "/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
      genre_ids: [10749, 18],
      id: 761053,
      original_language: "en",
      original_title: "Gabriel's Inferno: Part III",
      overview:
        "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
      popularity: 26.515,
      poster_path: "/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg",
      release_date: "2020-11-19",
      title: "Gabriel's Inferno: Part III",
      video: false,
      vote_average: 8.379,
      vote_count: 1047,
    },
    {
      adult: false,
      backdrop_path: "/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg",
      genre_ids: [16, 18],
      id: 378064,
      original_language: "ja",
      original_title: "映画 聲の形",
      overview:
        "Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?",
      popularity: 57.687,
      poster_path: "/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg",
      release_date: "2016-09-17",
      title: "A Silent Voice: The Movie",
      video: false,
      vote_average: 8.376,
      vote_count: 3825,
    },
    {
      adult: false,
      backdrop_path: "/wVJG3u5Ru9tInxYiTCrJr4MpJ7Z.jpg",
      genre_ids: [10402],
      id: 1160164,
      original_language: "en",
      original_title: "TAYLOR SWIFT | THE ERAS TOUR",
      overview:
        "The cultural phenomenon continues on the big screen! Immerse yourself in this once-in-a-lifetime concert film experience with a breathtaking, cinematic view of the history-making tour.",
      popularity: 44.422,
      poster_path: "/jf3YO8hOqGHCupsREf5qymYq1n.jpg",
      release_date: "2023-10-13",
      title: "TAYLOR SWIFT | THE ERAS TOUR",
      video: false,
      vote_average: 8.374,
      vote_count: 349,
    },
    {
      adult: false,
      backdrop_path: "/iwgl8zlrrfvfWp9k9Paj8lvFEvS.jpg",
      genre_ids: [80, 9648, 53],
      id: 807,
      original_language: "en",
      original_title: "Se7en",
      overview:
        'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
      popularity: 162.132,
      poster_path: "/6yoghtyTpznpBik8EngEmJskVUO.jpg",
      release_date: "1995-09-22",
      title: "Se7en",
      video: false,
      vote_average: 8.373,
      vote_count: 20482,
    },
    {
      adult: false,
      backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
      genre_ids: [28, 878, 12],
      id: 27205,
      original_language: "en",
      original_title: "Inception",
      overview:
        "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
      popularity: 233.155,
      poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
      release_date: "2010-07-15",
      title: "Inception",
      video: false,
      vote_average: 8.368,
      vote_count: 35922,
    },
    {
      adult: false,
      backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
      genre_ids: [16, 28, 12, 878],
      id: 569094,
      original_language: "en",
      original_title: "Spider-Man: Across the Spider-Verse",
      overview:
        "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
      popularity: 253.132,
      poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
      release_date: "2023-05-31",
      title: "Spider-Man: Across the Spider-Verse",
      video: false,
      vote_average: 8.364,
      vote_count: 6399,
    },
    {
      adult: false,
      backdrop_path: "/8aEe01VfGtYG2dFy9V5MqyyNPlh.jpg",
      genre_ids: [53, 9648],
      id: 567,
      original_language: "en",
      original_title: "Rear Window",
      overview:
        "A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.",
      popularity: 37.761,
      poster_path: "/ILVF0eJxHMddjxeQhswFtpMtqx.jpg",
      release_date: "1954-08-01",
      title: "Rear Window",
      video: false,
      vote_average: 8.353,
      vote_count: 6291,
    },
    {
      adult: false,
      backdrop_path: "/mfwq2nMBzArzQ7Y9RKE8SKeeTkg.jpg",
      genre_ids: [80, 18, 53],
      id: 274,
      original_language: "en",
      original_title: "The Silence of the Lambs",
      overview:
        "Clarice Starling is a top student at the FBI's training academy.  Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism.  Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.",
      popularity: 14.238,
      poster_path: "/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
      release_date: "1991-02-14",
      title: "The Silence of the Lambs",
      video: false,
      vote_average: 8.348,
      vote_count: 15860,
    },
    {
      adult: false,
      backdrop_path: "/6qHI1IYj7QlLSCwHRzkL62X175s.jpg",
      genre_ids: [18],
      id: 73,
      original_language: "en",
      original_title: "American History X",
      overview:
        "Derek Vineyard is paroled after serving 3 years in prison for killing two African-American men. Through his brother, Danny Vineyard's narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.",
      popularity: 89.28,
      poster_path: "/euypWkaYFOLW3e5rLIcTAjWnhhT.jpg",
      release_date: "1998-07-01",
      title: "American History X",
      video: false,
      vote_average: 8.346,
      vote_count: 11279,
    },
    {
      adult: false,
      backdrop_path: "/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg",
      genre_ids: [12, 14, 16],
      id: 128,
      original_language: "ja",
      original_title: "もののけ姫",
      overview:
        "Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
      popularity: 90.757,
      poster_path: "/cMYCDADoLKLbB83g4WnJegaZimC.jpg",
      release_date: "1997-07-12",
      title: "Princess Mononoke",
      video: false,
      vote_average: 8.339,
      vote_count: 7750,
    },
    {
      adult: false,
      backdrop_path: "/jBIMZ0AlUYuFNsKbd4L6FojWMoy.jpg",
      genre_ids: [16, 35, 10749],
      id: 820067,
      original_language: "ja",
      original_title: "映画 五等分の花嫁",
      overview:
        "When five lovely young girls who hate studying hire part-time tutor Futaro, he guides not only their education but also their hearts. Time spent has brought them all closer, with feelings growing within the girls and Futaro. As they finish their third year of high school and their last school festival approaches, they set their sights on what’s next. Is there a future with one of them and Futaro?",
      popularity: 32.113,
      poster_path: "/sg7klpt1xwK1IJirBI9EHaqQwJ5.jpg",
      release_date: "2022-05-20",
      title: "The Quintessential Quintuplets Movie",
      video: false,
      vote_average: 8.333,
      vote_count: 362,
    },
    {
      adult: false,
      backdrop_path: "/8KJMOKyl9rpgb9ELEwhfBMIaTHw.jpg",
      genre_ids: [16, 10751, 14, 35],
      id: 1139087,
      original_language: "en",
      original_title: "Once Upon a Studio",
      overview:
        "Created for Disney's 100th anniversary, the short features Mickey Mouse corralling a gallery of legendary Disney characters for a group photo.",
      popularity: 38.837,
      poster_path: "/aiy3G1cYWV3LgKZHY6a3jL8bjYL.jpg",
      release_date: "2023-09-24",
      title: "Once Upon a Studio",
      video: false,
      vote_average: 8.324,
      vote_count: 326,
    },
    {
      adult: false,
      backdrop_path: "/qknxyRgP6UTmwJ4B9tDAmzHMq7u.jpg",
      genre_ids: [10749, 16, 14],
      id: 92321,
      original_language: "ja",
      original_title: "蛍火の杜へ",
      overview:
        "One hot summer day a little girl gets lost in an enchanted forest of the mountain god where spirits reside. A young boy appears before her, but she cannot touch him for fear of making him disappear. And so a wondrous adventure awaits...",
      popularity: 0.038,
      poster_path: "/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg",
      release_date: "2011-09-17",
      title: "Hotarubi no Mori e",
      video: false,
      vote_average: 8.324,
      vote_count: 1077,
    },
    {
      adult: false,
      backdrop_path: "/c8Pi8F1FzpNebtgXcSjC9nWCdSW.jpg",
      genre_ids: [35, 10752],
      id: 914,
      original_language: "en",
      original_title: "The Great Dictator",
      overview:
        "Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.",
      popularity: 71.459,
      poster_path: "/1QpO9wo7JWecZ4NiBuu625FiY1j.jpg",
      release_date: "1940-10-15",
      title: "The Great Dictator",
      video: false,
      vote_average: 8.322,
      vote_count: 3259,
    },
    {
      adult: false,
      backdrop_path: "/hxSB02ksqnkXY4hPGAXqgO2fL01.jpg",
      genre_ids: [12, 35, 878],
      id: 105,
      original_language: "en",
      original_title: "Back to the Future",
      overview:
        "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
      popularity: 127.722,
      poster_path: "/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg",
      release_date: "1985-07-03",
      title: "Back to the Future",
      video: false,
      vote_average: 8.318,
      vote_count: 19416,
    },
    {
      adult: false,
      backdrop_path: "/gSCT6oP2Sbm71naW28Lh7afcMgY.jpg",
      genre_ids: [18, 80, 9648],
      id: 12493,
      original_language: "ja",
      original_title: "天国と地獄",
      overview:
        "In the midst of an attempt to take over his company, a powerhouse executive is hit with a huge ransom demand when his servants son is kidnapped",
      popularity: 47.824,
      poster_path: "/tgNjemQPG96uIezpiUiXFcer5ga.jpg",
      release_date: "1963-03-01",
      title: "High and Low",
      video: false,
      vote_average: 8.317,
      vote_count: 846,
    },
    {
      adult: false,
      backdrop_path: "/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg",
      genre_ids: [28, 18, 36],
      id: 14537,
      original_language: "ja",
      original_title: "切腹",
      overview:
        "Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.",
      popularity: 18.081,
      poster_path: "/5konZnIbcAxZjP616Cz5o9bKEfW.jpg",
      release_date: "1962-09-15",
      title: "Harakiri",
      video: false,
      vote_average: 8.4,
      vote_count: 947,
    },
    {
      adult: false,
      backdrop_path: "/aJCtkxLLzkk1pECehVjKHA2lBgw.jpg",
      genre_ids: [12, 28, 878],
      id: 1891,
      original_language: "en",
      original_title: "The Empire Strikes Back",
      overview:
        "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
      popularity: 32.885,
      poster_path: "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
      release_date: "1980-05-20",
      title: "The Empire Strikes Back",
      video: false,
      vote_average: 8.4,
      vote_count: 16553,
    },
    {
      adult: false,
      backdrop_path: "/dVr11o9or7AS8AMPfwjSpEU83iU.jpg",
      genre_ids: [18, 10752],
      id: 423,
      original_language: "en",
      original_title: "The Pianist",
      overview:
        "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
      popularity: 45.136,
      poster_path: "/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
      release_date: "2002-09-17",
      title: "The Pianist",
      video: false,
      vote_average: 8.385,
      vote_count: 8915,
    },
    {
      adult: false,
      backdrop_path: "/x9jRnHZlmApkYFMz2mc1E0cfTz9.jpg",
      genre_ids: [18, 10402],
      id: 244786,
      original_language: "en",
      original_title: "Whiplash",
      overview:
        "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
      popularity: 116.451,
      poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
      release_date: "2014-10-10",
      title: "Whiplash",
      video: false,
      vote_average: 8.381,
      vote_count: 14706,
    },
    {
      adult: false,
      backdrop_path: "/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
      genre_ids: [10749, 18],
      id: 761053,
      original_language: "en",
      original_title: "Gabriel's Inferno: Part III",
      overview:
        "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
      popularity: 26.515,
      poster_path: "/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg",
      release_date: "2020-11-19",
      title: "Gabriel's Inferno: Part III",
      video: false,
      vote_average: 8.379,
      vote_count: 1047,
    },
    {
      adult: false,
      backdrop_path: "/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg",
      genre_ids: [16, 18],
      id: 378064,
      original_language: "ja",
      original_title: "映画 聲の形",
      overview:
        "Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?",
      popularity: 57.687,
      poster_path: "/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg",
      release_date: "2016-09-17",
      title: "A Silent Voice: The Movie",
      video: false,
      vote_average: 8.376,
      vote_count: 3825,
    },
    {
      adult: false,
      backdrop_path: "/wVJG3u5Ru9tInxYiTCrJr4MpJ7Z.jpg",
      genre_ids: [10402],
      id: 1160164,
      original_language: "en",
      original_title: "TAYLOR SWIFT | THE ERAS TOUR",
      overview:
        "The cultural phenomenon continues on the big screen! Immerse yourself in this once-in-a-lifetime concert film experience with a breathtaking, cinematic view of the history-making tour.",
      popularity: 44.422,
      poster_path: "/jf3YO8hOqGHCupsREf5qymYq1n.jpg",
      release_date: "2023-10-13",
      title: "TAYLOR SWIFT | THE ERAS TOUR",
      video: false,
      vote_average: 8.374,
      vote_count: 349,
    },
    {
      adult: false,
      backdrop_path: "/iwgl8zlrrfvfWp9k9Paj8lvFEvS.jpg",
      genre_ids: [80, 9648, 53],
      id: 807,
      original_language: "en",
      original_title: "Se7en",
      overview:
        'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
      popularity: 162.132,
      poster_path: "/6yoghtyTpznpBik8EngEmJskVUO.jpg",
      release_date: "1995-09-22",
      title: "Se7en",
      video: false,
      vote_average: 8.373,
      vote_count: 20482,
    },
    {
      adult: false,
      backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
      genre_ids: [28, 878, 12],
      id: 27205,
      original_language: "en",
      original_title: "Inception",
      overview:
        "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
      popularity: 233.155,
      poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
      release_date: "2010-07-15",
      title: "Inception",
      video: false,
      vote_average: 8.368,
      vote_count: 35922,
    },
    {
      adult: false,
      backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
      genre_ids: [16, 28, 12, 878],
      id: 569094,
      original_language: "en",
      original_title: "Spider-Man: Across the Spider-Verse",
      overview:
        "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
      popularity: 253.132,
      poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
      release_date: "2023-05-31",
      title: "Spider-Man: Across the Spider-Verse",
      video: false,
      vote_average: 8.364,
      vote_count: 6399,
    },
    {
      adult: false,
      backdrop_path: "/8aEe01VfGtYG2dFy9V5MqyyNPlh.jpg",
      genre_ids: [53, 9648],
      id: 567,
      original_language: "en",
      original_title: "Rear Window",
      overview:
        "A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.",
      popularity: 37.761,
      poster_path: "/ILVF0eJxHMddjxeQhswFtpMtqx.jpg",
      release_date: "1954-08-01",
      title: "Rear Window",
      video: false,
      vote_average: 8.353,
      vote_count: 6291,
    },
    {
      adult: false,
      backdrop_path: "/mfwq2nMBzArzQ7Y9RKE8SKeeTkg.jpg",
      genre_ids: [80, 18, 53],
      id: 274,
      original_language: "en",
      original_title: "The Silence of the Lambs",
      overview:
        "Clarice Starling is a top student at the FBI's training academy.  Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism.  Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.",
      popularity: 14.238,
      poster_path: "/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
      release_date: "1991-02-14",
      title: "The Silence of the Lambs",
      video: false,
      vote_average: 8.348,
      vote_count: 15860,
    },
    {
      adult: false,
      backdrop_path: "/6qHI1IYj7QlLSCwHRzkL62X175s.jpg",
      genre_ids: [18],
      id: 73,
      original_language: "en",
      original_title: "American History X",
      overview:
        "Derek Vineyard is paroled after serving 3 years in prison for killing two African-American men. Through his brother, Danny Vineyard's narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.",
      popularity: 89.28,
      poster_path: "/euypWkaYFOLW3e5rLIcTAjWnhhT.jpg",
      release_date: "1998-07-01",
      title: "American History X",
      video: false,
      vote_average: 8.346,
      vote_count: 11279,
    },
    {
      adult: false,
      backdrop_path: "/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg",
      genre_ids: [12, 14, 16],
      id: 128,
      original_language: "ja",
      original_title: "もののけ姫",
      overview:
        "Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
      popularity: 90.757,
      poster_path: "/cMYCDADoLKLbB83g4WnJegaZimC.jpg",
      release_date: "1997-07-12",
      title: "Princess Mononoke",
      video: false,
      vote_average: 8.339,
      vote_count: 7750,
    },
    {
      adult: false,
      backdrop_path: "/jBIMZ0AlUYuFNsKbd4L6FojWMoy.jpg",
      genre_ids: [16, 35, 10749],
      id: 820067,
      original_language: "ja",
      original_title: "映画 五等分の花嫁",
      overview:
        "When five lovely young girls who hate studying hire part-time tutor Futaro, he guides not only their education but also their hearts. Time spent has brought them all closer, with feelings growing within the girls and Futaro. As they finish their third year of high school and their last school festival approaches, they set their sights on what’s next. Is there a future with one of them and Futaro?",
      popularity: 32.113,
      poster_path: "/sg7klpt1xwK1IJirBI9EHaqQwJ5.jpg",
      release_date: "2022-05-20",
      title: "The Quintessential Quintuplets Movie",
      video: false,
      vote_average: 8.333,
      vote_count: 362,
    },
    {
      adult: false,
      backdrop_path: "/8KJMOKyl9rpgb9ELEwhfBMIaTHw.jpg",
      genre_ids: [16, 10751, 14, 35],
      id: 1139087,
      original_language: "en",
      original_title: "Once Upon a Studio",
      overview:
        "Created for Disney's 100th anniversary, the short features Mickey Mouse corralling a gallery of legendary Disney characters for a group photo.",
      popularity: 38.837,
      poster_path: "/aiy3G1cYWV3LgKZHY6a3jL8bjYL.jpg",
      release_date: "2023-09-24",
      title: "Once Upon a Studio",
      video: false,
      vote_average: 8.324,
      vote_count: 326,
    },
    {
      adult: false,
      backdrop_path: "/qknxyRgP6UTmwJ4B9tDAmzHMq7u.jpg",
      genre_ids: [10749, 16, 14],
      id: 92321,
      original_language: "ja",
      original_title: "蛍火の杜へ",
      overview:
        "One hot summer day a little girl gets lost in an enchanted forest of the mountain god where spirits reside. A young boy appears before her, but she cannot touch him for fear of making him disappear. And so a wondrous adventure awaits...",
      popularity: 0.038,
      poster_path: "/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg",
      release_date: "2011-09-17",
      title: "Hotarubi no Mori e",
      video: false,
      vote_average: 8.324,
      vote_count: 1077,
    },
    {
      adult: false,
      backdrop_path: "/c8Pi8F1FzpNebtgXcSjC9nWCdSW.jpg",
      genre_ids: [35, 10752],
      id: 914,
      original_language: "en",
      original_title: "The Great Dictator",
      overview:
        "Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.",
      popularity: 71.459,
      poster_path: "/1QpO9wo7JWecZ4NiBuu625FiY1j.jpg",
      release_date: "1940-10-15",
      title: "The Great Dictator",
      video: false,
      vote_average: 8.322,
      vote_count: 3259,
    },
    {
      adult: false,
      backdrop_path: "/hxSB02ksqnkXY4hPGAXqgO2fL01.jpg",
      genre_ids: [12, 35, 878],
      id: 105,
      original_language: "en",
      original_title: "Back to the Future",
      overview:
        "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
      popularity: 127.722,
      poster_path: "/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg",
      release_date: "1985-07-03",
      title: "Back to the Future",
      video: false,
      vote_average: 8.318,
      vote_count: 19416,
    },
    {
      adult: false,
      backdrop_path: "/gSCT6oP2Sbm71naW28Lh7afcMgY.jpg",
      genre_ids: [18, 80, 9648],
      id: 12493,
      original_language: "ja",
      original_title: "天国と地獄",
      overview:
        "In the midst of an attempt to take over his company, a powerhouse executive is hit with a huge ransom demand when his servants son is kidnapped",
      popularity: 47.824,
      poster_path: "/tgNjemQPG96uIezpiUiXFcer5ga.jpg",
      release_date: "1963-03-01",
      title: "High and Low",
      video: false,
      vote_average: 8.317,
      vote_count: 846,
    },
    {
      adult: false,
      backdrop_path: "/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg",
      genre_ids: [28, 18, 36],
      id: 14537,
      original_language: "ja",
      original_title: "切腹",
      overview:
        "Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.",
      popularity: 18.081,
      poster_path: "/5konZnIbcAxZjP616Cz5o9bKEfW.jpg",
      release_date: "1962-09-15",
      title: "Harakiri",
      video: false,
      vote_average: 8.4,
      vote_count: 947,
    },
    {
      adult: false,
      backdrop_path: "/aJCtkxLLzkk1pECehVjKHA2lBgw.jpg",
      genre_ids: [12, 28, 878],
      id: 1891,
      original_language: "en",
      original_title: "The Empire Strikes Back",
      overview:
        "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
      popularity: 32.885,
      poster_path: "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
      release_date: "1980-05-20",
      title: "The Empire Strikes Back",
      video: false,
      vote_average: 8.4,
      vote_count: 16553,
    },
    {
      adult: false,
      backdrop_path: "/dVr11o9or7AS8AMPfwjSpEU83iU.jpg",
      genre_ids: [18, 10752],
      id: 423,
      original_language: "en",
      original_title: "The Pianist",
      overview:
        "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
      popularity: 45.136,
      poster_path: "/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
      release_date: "2002-09-17",
      title: "The Pianist",
      video: false,
      vote_average: 8.385,
      vote_count: 8915,
    },
    {
      adult: false,
      backdrop_path: "/x9jRnHZlmApkYFMz2mc1E0cfTz9.jpg",
      genre_ids: [18, 10402],
      id: 244786,
      original_language: "en",
      original_title: "Whiplash",
      overview:
        "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
      popularity: 116.451,
      poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
      release_date: "2014-10-10",
      title: "Whiplash",
      video: false,
      vote_average: 8.381,
      vote_count: 14706,
    },
    {
      adult: false,
      backdrop_path: "/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
      genre_ids: [10749, 18],
      id: 761053,
      original_language: "en",
      original_title: "Gabriel's Inferno: Part III",
      overview:
        "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
      popularity: 26.515,
      poster_path: "/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg",
      release_date: "2020-11-19",
      title: "Gabriel's Inferno: Part III",
      video: false,
      vote_average: 8.379,
      vote_count: 1047,
    },
    {
      adult: false,
      backdrop_path: "/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg",
      genre_ids: [16, 18],
      id: 378064,
      original_language: "ja",
      original_title: "映画 聲の形",
      overview:
        "Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?",
      popularity: 57.687,
      poster_path: "/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg",
      release_date: "2016-09-17",
      title: "A Silent Voice: The Movie",
      video: false,
      vote_average: 8.376,
      vote_count: 3825,
    },
    {
      adult: false,
      backdrop_path: "/wVJG3u5Ru9tInxYiTCrJr4MpJ7Z.jpg",
      genre_ids: [10402],
      id: 1160164,
      original_language: "en",
      original_title: "TAYLOR SWIFT | THE ERAS TOUR",
      overview:
        "The cultural phenomenon continues on the big screen! Immerse yourself in this once-in-a-lifetime concert film experience with a breathtaking, cinematic view of the history-making tour.",
      popularity: 44.422,
      poster_path: "/jf3YO8hOqGHCupsREf5qymYq1n.jpg",
      release_date: "2023-10-13",
      title: "TAYLOR SWIFT | THE ERAS TOUR",
      video: false,
      vote_average: 8.374,
      vote_count: 349,
    },
    {
      adult: false,
      backdrop_path: "/iwgl8zlrrfvfWp9k9Paj8lvFEvS.jpg",
      genre_ids: [80, 9648, 53],
      id: 807,
      original_language: "en",
      original_title: "Se7en",
      overview:
        'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
      popularity: 162.132,
      poster_path: "/6yoghtyTpznpBik8EngEmJskVUO.jpg",
      release_date: "1995-09-22",
      title: "Se7en",
      video: false,
      vote_average: 8.373,
      vote_count: 20482,
    },
    {
      adult: false,
      backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
      genre_ids: [28, 878, 12],
      id: 27205,
      original_language: "en",
      original_title: "Inception",
      overview:
        "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
      popularity: 233.155,
      poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
      release_date: "2010-07-15",
      title: "Inception",
      video: false,
      vote_average: 8.368,
      vote_count: 35922,
    },
    {
      adult: false,
      backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
      genre_ids: [16, 28, 12, 878],
      id: 569094,
      original_language: "en",
      original_title: "Spider-Man: Across the Spider-Verse",
      overview:
        "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
      popularity: 253.132,
      poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
      release_date: "2023-05-31",
      title: "Spider-Man: Across the Spider-Verse",
      video: false,
      vote_average: 8.364,
      vote_count: 6399,
    },
    {
      adult: false,
      backdrop_path: "/8aEe01VfGtYG2dFy9V5MqyyNPlh.jpg",
      genre_ids: [53, 9648],
      id: 567,
      original_language: "en",
      original_title: "Rear Window",
      overview:
        "A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.",
      popularity: 37.761,
      poster_path: "/ILVF0eJxHMddjxeQhswFtpMtqx.jpg",
      release_date: "1954-08-01",
      title: "Rear Window",
      video: false,
      vote_average: 8.353,
      vote_count: 6291,
    },
    {
      adult: false,
      backdrop_path: "/mfwq2nMBzArzQ7Y9RKE8SKeeTkg.jpg",
      genre_ids: [80, 18, 53],
      id: 274,
      original_language: "en",
      original_title: "The Silence of the Lambs",
      overview:
        "Clarice Starling is a top student at the FBI's training academy.  Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism.  Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.",
      popularity: 14.238,
      poster_path: "/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
      release_date: "1991-02-14",
      title: "The Silence of the Lambs",
      video: false,
      vote_average: 8.348,
      vote_count: 15860,
    },
    {
      adult: false,
      backdrop_path: "/6qHI1IYj7QlLSCwHRzkL62X175s.jpg",
      genre_ids: [18],
      id: 73,
      original_language: "en",
      original_title: "American History X",
      overview:
        "Derek Vineyard is paroled after serving 3 years in prison for killing two African-American men. Through his brother, Danny Vineyard's narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.",
      popularity: 89.28,
      poster_path: "/euypWkaYFOLW3e5rLIcTAjWnhhT.jpg",
      release_date: "1998-07-01",
      title: "American History X",
      video: false,
      vote_average: 8.346,
      vote_count: 11279,
    },
    {
      adult: false,
      backdrop_path: "/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg",
      genre_ids: [12, 14, 16],
      id: 128,
      original_language: "ja",
      original_title: "もののけ姫",
      overview:
        "Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
      popularity: 90.757,
      poster_path: "/cMYCDADoLKLbB83g4WnJegaZimC.jpg",
      release_date: "1997-07-12",
      title: "Princess Mononoke",
      video: false,
      vote_average: 8.339,
      vote_count: 7750,
    },
    {
      adult: false,
      backdrop_path: "/jBIMZ0AlUYuFNsKbd4L6FojWMoy.jpg",
      genre_ids: [16, 35, 10749],
      id: 820067,
      original_language: "ja",
      original_title: "映画 五等分の花嫁",
      overview:
        "When five lovely young girls who hate studying hire part-time tutor Futaro, he guides not only their education but also their hearts. Time spent has brought them all closer, with feelings growing within the girls and Futaro. As they finish their third year of high school and their last school festival approaches, they set their sights on what’s next. Is there a future with one of them and Futaro?",
      popularity: 32.113,
      poster_path: "/sg7klpt1xwK1IJirBI9EHaqQwJ5.jpg",
      release_date: "2022-05-20",
      title: "The Quintessential Quintuplets Movie",
      video: false,
      vote_average: 8.333,
      vote_count: 362,
    },
    {
      adult: false,
      backdrop_path: "/8KJMOKyl9rpgb9ELEwhfBMIaTHw.jpg",
      genre_ids: [16, 10751, 14, 35],
      id: 1139087,
      original_language: "en",
      original_title: "Once Upon a Studio",
      overview:
        "Created for Disney's 100th anniversary, the short features Mickey Mouse corralling a gallery of legendary Disney characters for a group photo.",
      popularity: 38.837,
      poster_path: "/aiy3G1cYWV3LgKZHY6a3jL8bjYL.jpg",
      release_date: "2023-09-24",
      title: "Once Upon a Studio",
      video: false,
      vote_average: 8.324,
      vote_count: 326,
    },
    {
      adult: false,
      backdrop_path: "/qknxyRgP6UTmwJ4B9tDAmzHMq7u.jpg",
      genre_ids: [10749, 16, 14],
      id: 92321,
      original_language: "ja",
      original_title: "蛍火の杜へ",
      overview:
        "One hot summer day a little girl gets lost in an enchanted forest of the mountain god where spirits reside. A young boy appears before her, but she cannot touch him for fear of making him disappear. And so a wondrous adventure awaits...",
      popularity: 0.038,
      poster_path: "/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg",
      release_date: "2011-09-17",
      title: "Hotarubi no Mori e",
      video: false,
      vote_average: 8.324,
      vote_count: 1077,
    },
    {
      adult: false,
      backdrop_path: "/c8Pi8F1FzpNebtgXcSjC9nWCdSW.jpg",
      genre_ids: [35, 10752],
      id: 914,
      original_language: "en",
      original_title: "The Great Dictator",
      overview:
        "Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.",
      popularity: 71.459,
      poster_path: "/1QpO9wo7JWecZ4NiBuu625FiY1j.jpg",
      release_date: "1940-10-15",
      title: "The Great Dictator",
      video: false,
      vote_average: 8.322,
      vote_count: 3259,
    },
    {
      adult: false,
      backdrop_path: "/hxSB02ksqnkXY4hPGAXqgO2fL01.jpg",
      genre_ids: [12, 35, 878],
      id: 105,
      original_language: "en",
      original_title: "Back to the Future",
      overview:
        "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
      popularity: 127.722,
      poster_path: "/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg",
      release_date: "1985-07-03",
      title: "Back to the Future",
      video: false,
      vote_average: 8.318,
      vote_count: 19416,
    },
    {
      adult: false,
      backdrop_path: "/gSCT6oP2Sbm71naW28Lh7afcMgY.jpg",
      genre_ids: [18, 80, 9648],
      id: 12493,
      original_language: "ja",
      original_title: "天国と地獄",
      overview:
        "In the midst of an attempt to take over his company, a powerhouse executive is hit with a huge ransom demand when his servants son is kidnapped",
      popularity: 47.824,
      poster_path: "/tgNjemQPG96uIezpiUiXFcer5ga.jpg",
      release_date: "1963-03-01",
      title: "High and Low",
      video: false,
      vote_average: 8.317,
      vote_count: 846,
    },
  ],
  total_pages: 473,
  total_results: 9460,
};
